config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  
  # Defines my routes #
  root "pa_leva#start"
  get '/pa-leva/session', to: "pa_leva#session"
  get '/pa-leva/details', to: "pa_leva#details"

  devise_for :user_owners
  devise_for :user_employees
  resources :employee_pre_registrations, only: [ :index, :new, :create ]

  resources :establishments, only: [ :new, :create, :show, :edit, :update ] do
    get "search", on: :collection
  end

  resources :dishes, only: [ :index, :new, :create, :show, :edit, :update ] do
    resources :portions, only: [ :new, :create, :show, :edit, :update ]
    resources :additional_features, only: [ :new, :create, :edit, :update ]
    patch "change_status", on: :member
    get "search", on: :collection
  end

  resources :beverages, only: [ :index, :new, :create, :show, :edit, :update ] do
    resources :portions, only: [ :new, :create, :show, :edit, :update ]
    patch "change_status", on: :member
  end

  resources :menus, only: [ :index, :new, :create, :show, :edit, :update ] do
    patch "change_status", on: :member
    post "add_item_to_order", on: :member
    delete "remove_item_from_order", on: :member
  end

  resources :orders, only: [ :index, :new, :create, :show ] do
    get "search", on: :collection
  end

  namespace :api do
    namespace :v1 do
      resources :establishments, param: :code, only: [] do
        resources :orders, param: :order_code, only: [:index, :show, :update] do
          patch :cancel, on: :member
        end
      end
    end
  end

end

app/models/beverage.rb
class Beverage < ApplicationRecord
  belongs_to :establishment
  has_one_attached :photo
  has_many :portions
  has_many :menu_beverages, dependent: :destroy
  has_many :menus, through: :menu_beverages
  has_many :order_items

  validates :name, :description, presence: true
end

app/controllers/beverages_controller.rb
class BeveragesController < ApplicationController
  before_action :authenticate_user_owner!
  before_action :set_params_and_check_user_owner, only: [:show, :edit, :update, :change_status]
  def index
    @beverages = current_user_owner.establishment.beverages

    if params[:alcoholic] == 'true'
      @beverages = @beverages.where(alcoholic: true)
    elsif params[:alcoholic] == 'false'
      @beverages = @beverages.where(alcoholic: false)
    end
  end

  def new
    @beverage = Beverage.new
  end

  def create
    @beverage = Beverage.new(save_params)
    @beverage.establishment = current_user_owner.establishment

    if @beverage.save
      redirect_to beverages_path, notice: "Bebida cadastrada com sucesso!"
    else
      flash.now[:alert] = "Falha ao cadastrar bebida"
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def edit; end

  def update
    if @beverage.update(save_params)
      redirect_to @beverage, notice: "Bebida atualizado com sucesso."
    else
      flash.now[:alert] = "Falha ao cadastrar bebida"
      render :edit, status: :unprocessable_entity
    end
  end

  def change_status
    @beverage.status = !@beverage.status
    if @beverage.save
      redirect_to @beverage, notice: 'Status da bebida atualizado com sucesso.'
    else
      redirect_to @beverage, alert: 'Não foi possível atualizar o status da bebida.'
    end
  end
  
  private

  def set_params_and_check_user_owner
    @beverage = Beverage.find(params[:id])
    if @beverage.establishment.user_owner != current_user_owner
      return redirect_to root_path, notice: "Você não possui acesso a esta bebida."
    end
  end

  def save_params
    params.require(:beverage).permit(:name, :description, :alcoholic, :calories, :photo)
  end
end

app/views/beverages/_form.html.erb
<%= form_with model: @beverage do |f| %>
    <div class="text-start">
        <%= f.label :name, class: 'form-label' %>
        <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="text-start">
        <%= f.label :description, class: 'form-label' %>
        <%= f.text_field :description, class: 'form-control'%>
    </div>
    <div class="text-start">
        <%= f.label :calories, class: 'form-label' %>
        <%= f.text_field :calories, class: 'form-control' %>
    </div>
    <div class="form-check form-switch form-check-reverse text-end">
        <%= f.label :alcoholic, class: 'form-check-label' %>
        <%= f.check_box :alcoholic, class: 'form-check-input' %>
    </div>
    <div class="text-start">
        <%= f.label :photo, "Foto da Bebida", class: 'form-label' %>
        <%= f.file_field :photo, class: 'form-control' %>
    </div>
    <br>
    <div>
        <%= link_to 'voltar', @beverage, class: 'btn btn-outline-dark' %>
        <%= f.submit 'Salvar', class: 'btn btn-outline-warning' %>
    </div>
<% end %>

app/views/beverages/edit.html.erb
<h3>Edite os campos que desejar</h3>
<%= render 'form' %>

app/views/beverages/index.html.erb
<h1>Bebidas Disponíveis</h1><br>

<div class="btn-group btn-group-sm" aria-label="Small button group">
    <%= link_to 'Alcoólicas', beverages_path(alcoholic: true), class: 'btn btn-outline-secondary btn-sm' %>
    <%= link_to 'Não Alcoólicas', beverages_path(alcoholic: false), class: 'btn btn-outline-secondary btn-sm' %>
    <%= link_to 'Todas', beverages_path, class: 'btn btn-outline-dark btn-sm' %>
</div><br>

<% if @beverages.any? %>
    <br>
    <% @beverages.each do |b| %>
        <div class="list-group">
            <div class="d-grid gap-2 d-md-flex justify-content-md-center">
                <%= link_to b.name, beverage_path(b), class: 'list-group-item list-group-item-action' %> <span class="list-group-item"><%= b.status ? 'Ativado' : 'Desativado' %></span>
            </div>
        </div>
        <br>
    <% end %>
<% else %>
    <p>Nenhuma bebida disponível</p>
<% end %>

<%= link_to 'Cadastrar Bebida', new_beverage_path, class: 'btn btn-warning' %>

app/views/beverages/new.html.erb
<h3>Cadastrar Bebida</h3>

<% if(@beverage.errors.any?) %>
    <h4>Verifique esse problemas:</h4>
    <% @beverage.errors.full_messages.each do |msg| %>
        - <%= msg %> <br>
    <% end %>
    <br>
<% end %>

<%= render 'form' %>

app/views/beverages/show.html.erb
<div class="card mb-3" style="max-width: 540px;"">
    <div class="row g-0">
        <div class="col-md-4 d-flex justify-content-center align-items-center">
            <% if @beverage.photo.attached? %>
                <%= image_tag @beverage.photo, width: 150, height: 150, class: 'card-img-top', style: 'padding-left: 10px;' %>
            <% else %>
                <p>Sem foto disponível</p>
            <% end %>
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h2 class="card-title"><%= @beverage.name %></h2>
                <h4 class="card-text"><%= @beverage.description %></h4>
                <h6 class="card-text"><%= @beverage.calories %> calorias</h6>
                <% if @beverage.alcoholic? %>
                    <p class="card-text"><small class="text-body-secondary">Bebida Alcoolica! (+18)</small></p>
                <% else %>
                    <p class="card-text"><small class="text-body-secondary">Não Alcoolica</small></p>
                <% end %>
                <small class="text-body-secondary">Status da Bebida: <%= @beverage.status ? 'Ativado' : 'Desativado' %></small>
            </div>
        </div>
    </div>
</div>
<br>

<div>
  <% if @beverage.portions.any? %>
    <h2>Porções</h2>
    <% @beverage.portions.each do |portion| %>
      <p>
        <b><%= portion.description %>:</b> <%= number_to_currency(portion.price) %>
        <%= link_to 'Editar', edit_beverage_portion_path(@beverage, portion), class: 'btn btn-outline-warning btn-sm' %>
        <%= link_to 'Histórico', beverage_portion_path(@beverage, portion), class: 'btn btn-outline-secondary btn-sm' %>
      </p>
    <% end %>
  <% else %>
    <p>Sem porção disponível</p>
  <% end %>
  <%= link_to 'Adicionar Porção', new_beverage_portion_path(@beverage), class: 'btn btn-warning' %>
</div>
<br>

<div class="d-flex justify-content-center">
  <div class="row g-3 align-items-center">
    <div class="col-auto"><%= link_to 'voltar', beverages_path, class: 'btn btn-outline-dark' %></div>
    <div class="col-auto"><%= link_to 'editar', edit_beverage_path, class: 'btn btn-outline-warning' %></div>
    <div class="col-auto">
      <%= form_with url: change_status_beverage_path(@beverage), method: :patch do %>
        <%= hidden_field_tag :status, !@beverage.status %>
        <%= button_tag 'Desativar', type: 'submit', class: 'btn btn-outline-danger' if @beverage.status == true %>
        <%= button_tag 'Ativar', type: 'submit', class: 'btn btn-outline-success' if @beverage.status == false %>
      <% end %>
    </div>
  </div>
</div>