config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  
  # Defines my routes #
  root "pa_leva#start"
  get '/pa-leva/session', to: "pa_leva#session"
  get '/pa-leva/details', to: "pa_leva#details"

  devise_for :user_owners
  devise_for :user_employees
  resources :employee_pre_registrations, only: [ :index, :new, :create ]

  resources :establishments, only: [ :new, :create, :show, :edit, :update ] do
    get "search", on: :collection
  end

  resources :dishes, only: [ :index, :new, :create, :show, :edit, :update ] do
    resources :portions, only: [ :new, :create, :show, :edit, :update ]
    resources :additional_features, only: [ :new, :create, :edit, :update ]
    patch "change_status", on: :member
    get "search", on: :collection
  end

  resources :beverages, only: [ :index, :new, :create, :show, :edit, :update ] do
    resources :portions, only: [ :new, :create, :show, :edit, :update ]
    patch "change_status", on: :member
  end

  resources :menus, only: [ :index, :new, :create, :show, :edit, :update ] do
    patch "change_status", on: :member
    post "add_item_to_order", on: :member
    delete "remove_item_from_order", on: :member
  end

  resources :orders, only: [ :index, :new, :create, :show ] do
    get "search", on: :collection
  end

  namespace :api do
    namespace :v1 do
      resources :establishments, param: :code, only: [] do
        resources :orders, param: :order_code, only: [:index, :show, :update] do
          patch :cancel, on: :member
        end
      end
    end
  end

end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :establishment
  has_one_attached :photo
  has_many :portions, dependent: :destroy
  has_many :additional_features, dependent: :destroy
  has_many :menu_dishes, dependent: :destroy
  has_many :menus, through: :menu_dishes
  has_many :order_items

  validates :name, :description, presence: true
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :authenticate_user_owner!
  before_action :set_params_and_check_user_owner, only: [:show, :edit, :update, :change_status]
  def index
    @dishes = current_user_owner.establishment.dishes
  end

  def new
    @dish = Dish.new
  end

  def create
    @dish = Dish.new(save_params)
    @dish.establishment = current_user_owner.establishment

    if @dish.save
      redirect_to dishes_path, notice: "Prato cadastrado com sucesso!"
    else
      flash.now[:alert] = "Falha ao cadastrar prato"
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def edit; end

  def update
    if @dish.update(save_params)
      redirect_to @dish, notice: "Prato atualizado com sucesso."
    else
      flash.now[:alert] = "Falha ao atualizar prato"
      render :edit, status: :unprocessable_entity
    end
  end

  def change_status
    @dish.status = !@dish.status
    if @dish.save
      redirect_to @dish, notice: 'Status do prato atualizado com sucesso.'
    else
      redirect_to @dish, alert: 'Não foi possível atualizar o status do prato.'
    end
  end

  def search
    query = "%#{params[:query].downcase}%"
    @dishes = current_user_owner.establishment.dishes.joins(:additional_features).where('additional_features.name LIKE ?', query).distinct
  end

  private

  def set_params_and_check_user_owner
    @dish = Dish.find(params[:id])
    if @dish.establishment.user_owner != current_user_owner
      return redirect_to root_path, alert: "Você não possui acesso a este prato."
    end
  end
  
  def save_params
    params.require(:dish).permit(:name, :description, :calories, :photo)
  end
end

app/views/dishes/_form.html.erb
<%= form_with model: @dish, multipart: true do |f| %>
    <div class="text-start">
        <%= f.label :name, class: 'form-label' %>
        <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="text-start">
        <%= f.label :description, class: 'form-label' %>
        <%= f.text_field :description, class: 'form-control' %>
    </div>
    <div class="text-start">
        <%= f.label :calories, class: 'form-label' %>
        <%= f.number_field :calories, class: 'form-control' %>
    </div>
    <div class="text-start">
        <%= f.label :photo, "Foto do Prato", class: 'form-label' %>
        <%= f.file_field :photo, class: 'form-control' %>
    </div>
    <br>
    <div>
        <%= link_to 'voltar', @dish, class: 'btn btn-outline-dark' %>
        <%= f.submit 'Salvar', class: 'btn btn-outline-warning' %>
    </div>
<% end %>

app/views/dishes/edit.html.erb
<h3>Edite os campos que desejar</h3>
<%= render 'form' %>

app/views/dishes/index.html.erb
<h1>Pratos Disponíveis</h1><br>

<%= form_with url: search_dishes_path, method: :get, local: true do %>
    <div class="d-flex justify-content-center">
        <div class="row g-3 align-items-center">
            <div class="col-auto"><%= text_field_tag :query, params[:query], class: 'form-control', placeholder: 'Digite um Marcador' %></div>
            <div class="col-auto"><%= submit_tag 'Filtrar', class: 'btn btn-warning' %></div>
        </div>
    </div>
<% end %><br>

<% if @dishes.any? %>
    <br>
    <% @dishes.each do |d| %>
        <div class="list-group">
            <div class="d-grid gap-2 d-md-flex justify-content-md-center">
                <%= link_to d.name, dish_path(d), class: 'list-group-item list-group-item-action' %> <span class="list-group-item"><%= d.status ? 'Ativado' : 'Desativado' %></span>
            </div>
        </div>
        <br>
    <% end %>
<% else %>
    <p>Nenhum prato disponível</p>
<% end %><br>

<%= link_to 'Cadastrar Prato', new_dish_path, class: 'btn btn-warning' %>

app/views/dishes/new.html.erb
<h3>Cadastrar Prato</h3>

<% if(@dish.errors.any?) %>
    <h4>Verifique esse problemas:</h4>
    <% @dish.errors.full_messages.each do |msg| %>
        - <%= msg %> <br>
    <% end %> <br>
<% end %>

<%= render 'form' %>

app/views/dishes/search.html.erb
<% if @dishes.any? %>
  <p><b>Resultado de pratos com a tag pesquisada:</b></p><br>
  
  <% @dishes.each do |d| %>
    <div class="list-group">
      <div class="d-grid gap-2 d-md-flex justify-content-md-center">
        <%= link_to d.name, dish_path(d), class: 'list-group-item list-group-item-action' %> <span class="list-group-item"><%= d.status ? 'Ativado' : 'Desativado' %></span>
      </div><br>
    </div>
  <% end %>
  
<% else %>
  <p>Nenhum prato disponível</p>
<% end %><br>

<%= link_to 'Voltar', dishes_path, class: 'btn btn-outline-dark' %>

app/views/dishes/show.html.erb
<div class="card" style="width: 25rem;">
    <div class="card-body">
        <h1 class="card-title"><%= @dish.name %></h1>
        <h3 class="card-text"><%= @dish.description %></h3>
        <h6 class="card-text"><%= @dish.calories %> calorias</h6>
        <p class="card-text">
          <small class="text-body-secondary">Prato <%= @dish.status ? 'Ativo' : 'Desativado' %></small>
        </p>
    </div>
    <% if @dish.photo.attached? %>
        <%= image_tag @dish.photo, class: 'card-img-top' %>
    <% else %>
        <p>Sem foto disponível</p>
    <% end %>
</div>
<br>

<div>
  <% if @dish.additional_features.any? %>
    <h3>Marcadores</h3>
    <% @dish.additional_features.each do |feature| %>
      <p>Prato <%= feature.name %></p>
    <% end %>
  <% else %>
    <p>Sem marcadores cadastrados</p>
  <% end %><br>
  <%= link_to 'Adicionar Marcador', new_dish_additional_feature_path(@dish), class: 'btn btn-warning btn-sm' %>
</div>
<br>

<div>
  <% if @dish.portions.any? %>
    <h3>Porções</h3>
    <% @dish.portions.each do |portion| %>
      <p>
        <b><%= portion.description %>:</b> <%= number_to_currency(portion.price) %>
        <%= link_to 'Editar', edit_dish_portion_path(@dish, portion), class: 'btn btn-outline-warning btn-sm' %>
        <%= link_to 'Histórico', dish_portion_path(@dish, portion), class: 'btn btn-outline-secondary btn-sm' %>
      </p>
    <% end %>
  <% else %>
    <p>Sem porção disponível</p>
  <% end %>
  <%= link_to 'Adicionar Porção', new_dish_portion_path(@dish), class: 'btn btn-warning btn-sm' %>
</div>
<br>

<div class="d-flex justify-content-center">
  <div class="row g-3 align-items-center">
    <div class="col-auto"><%= link_to 'voltar', dishes_path, class: 'btn btn-outline-dark' %></div>
    <div class="col-auto"><%= link_to 'editar', edit_dish_path, class: 'btn btn-outline-warning' %></div>
    <div class="col-auto">
      <%= form_with url: change_status_dish_path(@dish), method: :patch do %>
        <%= hidden_field_tag :status, !@dish.status %>
        <%= button_tag 'Desativar', type: 'submit', class: 'btn btn-outline-danger' if @dish.status == true %>
        <%= button_tag 'Ativar', type: 'submit', class: 'btn btn-outline-success' if @dish.status == false %>
      <% end %>
    </div>
  </div>
</div>