config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  
  # Defines my routes #
  root "pa_leva#start"
  get '/pa-leva/session', to: "pa_leva#session"
  get '/pa-leva/details', to: "pa_leva#details"

  devise_for :user_owners
  devise_for :user_employees
  resources :employee_pre_registrations, only: [ :index, :new, :create ]

  resources :establishments, only: [ :new, :create, :show, :edit, :update ] do
    get "search", on: :collection
  end

  resources :dishes, only: [ :index, :new, :create, :show, :edit, :update ] do
    resources :portions, only: [ :new, :create, :show, :edit, :update ]
    resources :additional_features, only: [ :new, :create, :edit, :update ]
    patch "change_status", on: :member
    get "search", on: :collection
  end

  resources :beverages, only: [ :index, :new, :create, :show, :edit, :update ] do
    resources :portions, only: [ :new, :create, :show, :edit, :update ]
    patch "change_status", on: :member
  end

  resources :menus, only: [ :index, :new, :create, :show, :edit, :update ] do
    patch "change_status", on: :member
    post "add_item_to_order", on: :member
    delete "remove_item_from_order", on: :member
  end

  resources :orders, only: [ :index, :new, :create, :show ] do
    get "search", on: :collection
  end

  namespace :api do
    namespace :v1 do
      resources :establishments, param: :code, only: [] do
        resources :orders, param: :order_code, only: [:index, :show, :update] do
          patch :cancel, on: :member
        end
      end
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "PaLevá" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" type="image/png" href="<%= image_url('android-chrome-512x512.png') %>">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <div class="header">
        <% if user_owner_signed_in? %>
          <div class="d-flex justify-content-center">
            <div class="row g-3 align-items-center">
              <div class="col-auto"><%= link_to 'PaLevá', pa_leva_details_path, class: 'btn btn-warning' %></div>
              <div class="col-auto">
                <b><%= current_user_owner.name %> <%= current_user_owner.last_name %></b><br>
                <%= current_user_owner.email %>
              </div>
              <div class="col-auto">
                <%= button_to 'Sair', destroy_user_owner_session_path, method: :delete, class: 'btn btn-outline-dark' %>
              </div>
              <div class="col-auto">
                <% if user_owner_signed_in? && !current_user_owner.establishment.nil? %>
                  <%= form_with url: search_establishments_path, method: :get, local: true do %>
                    <div class="d-flex justify-content-center">
                      <div class="row g-3 align-items-center">
                        <div class="col-auto"><%= text_field_tag :query, params[:query], class: 'form-control', placeholder: 'Buscar Item' %></div>
                        <div class="col-auto"><%= submit_tag 'Buscar', class: 'btn btn-warning' %></div>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
        <% if user_employee_signed_in? %>
          <div class="d-flex justify-content-center">
            <div class="row g-3 align-items-center">
              <div class="col-auto"><%= link_to 'PaLevá', menus_path, class: 'btn btn-primary' %></div>
              <div class="col-auto">
                <b style="color: #14213db3;"><%= current_user_employee.name %> <%= current_user_employee.last_name %></b><br>
                <%= current_user_employee.email %>
              </div>
              <div class="col-auto">
                <%= button_to 'Sair', destroy_user_employee_session_path, method: :delete, class: 'btn btn-outline-primary' %>
              </div>
            </div>
          </div>
        <% end %>
        <% unless user_owner_signed_in? || user_employee_signed_in? %>
          <div class="header-session">
            <%= link_to pa_leva_session_path do %>
              <%= image_tag 'android-chrome-192x192.png', class: 'img-fluid rounded-start', style: 'width: 70px' %>
            <% end %>
              <span>Estabelecimento!</span>
          </div>
        <% end %>
      </div>
      <nav>
        <% if user_owner_signed_in? && current_user_owner.establishment&.persisted? %>
          <div class="d-flex justify-content-center">
            <div class="row g-3 align-items-center">
              <div class="col-auto"><%= link_to 'Restaurante', establishment_path(current_user_owner.establishment), class: 'btn btn-warning btn-sm', style: 'border-color: black;' %></div>
              <div class="col-auto"><%= link_to 'Funcionários', employee_pre_registrations_path, class: 'btn btn-warning btn-sm', style: 'border-color: black;' %></div>
              <div class="col-auto"><%= link_to 'Pratos', dishes_path, class: 'btn btn-warning btn-sm', style: 'border-color: black;' %></div>
              <div class="col-auto"><%= link_to 'Bebidas', beverages_path, class: 'btn btn-warning btn-sm', style: 'border-color: black;' %></div>
              <div class="col-auto"><%= link_to 'Cardápios', menus_path, class: 'btn btn-warning btn-sm', style: 'border-color: black;' %></div>
              <div class="col-auto"><%= link_to 'Pedidos', orders_path, class: 'btn btn-warning btn-sm', style: 'border-color: black;' %></div>
            </div>
          </div>
        <% end %>
        <% if user_employee_signed_in? %>
          <div class="d-flex justify-content-center">
            <div class="row g-3 align-items-center">
              <div class="col-auto"><%= link_to 'Restaurante', establishment_path(current_user_employee.establishment), class: 'btn btn-primary btn-sm', style: 'background-color: #14213db3; border-color: black;' %></div>
              <div class="col-auto"><%= link_to 'Cardápios', menus_path, class: 'btn btn-primary btn-sm', style: 'background-color: #14213db3; border-color: black;' %></div>
              <div class="col-auto"><%= link_to 'Pedidos', orders_path, class: 'btn btn-primary btn-sm', style: 'background-color: #14213db3; border-color: black;' %></div>
            </div>
          </div>
        <% end %>
      </nav>
    </header>

    <main>
      <% if alert || notice %>
        <div class="d-flex justify-content-center">
          <div class="alert alert-warning" style="width: 28rem;">
            <%= alert %>
            <%= notice %>
          </div>
        </div>
      <% end %>
      <section>
        <%= yield %>
      </section>
    </main><br>

    <footer>
      <p>&copy;<a href="https://www.linkedin.com/in/marcos-grocha/" target="_blank"> marcos-grocha</a></p>
    </footer><br>
  </body>
</html>